### ISSUE TITLE
Pending Apps Appear in Find Apps (Which means flagged Apps!)

### ISSUE THREAD

**Issue by reedspool** [app-inventor-gallery/aig#100]
I asked the Beta to Flag an App, my App, namely: "Muahaha"

It received 5 flags, which correctly sent a notification to Derrell, and set the status of the App to "Pending"

The App no longer appears on the home page, but still comes up in Find Apps!    BUUUG!

Have fun cleaning up more of my summer work, Paul!

**Comment by derrell** [comment]
@cpuwhiz11 to you
