### ISSUE TITLE
Basic search in header of all pages

### ISSUE THREAD

**Issue by derrell** [app-inventor-gallery/aig#2]
See #1 for image.

In addition to the basic text box and "Search" button, add an "Advanced" link which directs to something like the current "Find Apps" page.

**Comment by derrell** [comment]
@fgmart I'm not sure this is necessary, and in fact, will make the interface less tidy. What are your thoughts?

**Comment by fgmart-zz** [comment]
I have never thought we need anything more than text box with associated search button.

Let me restate that -- I do think we want a "visual browse for similar" functionality.

E.g., you find some apps, you go to one, you see others by that author, you click on one, etc. and etc. forever.  We do want this.

**Comment by derrell** [comment]
Ok, but that's not answering my question. We have the "Apps by this author" feature in place. No problem there. Given that we already have a Find Apps top-level page, with the simple text search that you desire (and also a more sophisticated search feature), do we _also_ need the same simple text search in the header of every page? I think it's not, for the reasons mentioned above.

**Comment by fgmart-zz** [comment]
Sorry, I missed the "on all pages" portion of this.

No, we don't need that.

**Comment by derrell** [comment]
Thanks. Closing.
