### ISSUE TITLE
Modify browser's Location Bar URL for shortcuts

### ISSUE THREAD

**Issue by derrell** [app-inventor-gallery/aig#23]
If possible, modify the browser's location bar as each page is displayed, to provide a shortcut back to that same page.

**Comment by derrell** [comment]
qooxdoo has a "History" class that may assist with this. Even if the URL can't be modified in the Location bar, we may be able to show the shortcut using the History class (or otherwise) as a link that copies the shortcut to the clipboard.

**Comment by derrell** [comment]
This relates to #8.

**Comment by derrell** [comment]
See qooxdoo/application/playground/source/class/playground/Application.js and its use of qx.bom.History. We should be able to assign a unique URL to each page easily, and have it show up in the Location bar.

**Comment by derrell** [comment]
@cpuwhiz11 to you

**Comment by cpuwhiz11** [comment]
Issue is mostly complete. The url is modified depending on what page the user is on. This also allows the back and forward button to work as intended. Waiting for Find Apps page to be refactored to complete this issue.

**Comment by derrell** [comment]
Great. Does bookmarking a page and getting back to it later also work properly yet?

**Comment by cpuwhiz11** [comment]
Yes bookmarks are working. The actual name of the bookmark is not being updated, so that will be something I will have to look into.

**Comment by derrell** [comment]
Incorporated into master. Closing.

**Comment by derrell** [comment]
The view count is incremented twice now, when an app is visited. I have also noticed that I see the page display twice. This is likely due to the hash being set, so we need to figure out how to not reload the page.

**Comment by derrell** [comment]
The view count problem now has its own issue (#118). Closing this issue as its original intent is completed.
