### ISSUE TITLE
Search entity contains garbage

### ISSUE THREAD

**Issue by derrell** [app-inventor-gallery/aig#25]
The search object needs words to be stemmed better. Currently quotes, parenthesis, etc. are added to the Search entity type, as are some empty entries. Also, numbers are added but must be excluded.

**Comment by derrell** [comment]
I noticed that addOrEditApp() does:

```
        aiagallery.dbif.MApps._populateSearch(appObj.getData());
```

to create all of the search entries. It never, however, deletes entries from Search when an app is edited. For example, if I add an app with a description of, say, "Star Wars shooter," then later edit it to "Star Wars adventures," the word "shooter" never gets removed from the Search list.

**Comment by derrell** [comment]
@reedspool I've received no status for quite a while...

**Comment by reedspool** [comment]
Fixed! Tested and working to the point that we talked about. The only stemming i added was checking against the regex 

```
/[a-z0-9]{2,}/gi
```

So you'll have to decide if you want more in the future. The second problem there is also fixed; that is, search is updated when the app is updated. Pull Requesting now.

**Comment by derrell** [comment]
Reassigned to Paul.

**Comment by reedspool** [comment]
I am leaving this issue to Paul G. Here is the current state of affairs. 

The use of the regex to block invalid data is working, and tested in the final tests of the KeywordSearchTest. The quality of the regex currently in use is flimsy at best, but the system is working and easily adjustable.

Stop-words, which should never be added to the search db, are being added. They are being blocked from search results, though, so the framework for this block is loosely there.

The issue noted above by derrell, regarding query data being removed when an app is updated is FIXED and TESTED.

Currently, all the work of adding search data is being done in MApps.js. This has a proper home as a stub in MSearch.js, though, and shuold be moved there at some point. Good luck Paul

**Comment by cpuwhiz11** [comment]
There is no luck, only the force.

**Comment by derrell** [comment]
Do, or do not. There is no try.

**Comment by derrell** [comment]
Incorporated into master. Closing.
