### ISSUE TITLE
Pre-load qooxdoo classes

### ISSUE THREAD

**Issue by derrell** [app-inventor-gallery/aig#26]
Arrange for initialization to be accomplished when an instance of the RpcServlet is created, rather than waiting until the first RPC request is made.

**Comment by derrell** [comment]
Fixed with 06f595cfec2e8b15be45ddbcf7483e97ed080810

@fgmart Each request should now be satisfied far more quickly. Initialization happens once when an instance is started, instead of upon each RPC request.

**Comment by fgmart-zz** [comment]
yay
