### ISSUE TITLE
Implement Tab View equivalent using links

### ISSUE THREAD

**Issue by derrell** [app-inventor-gallery/aig#3]
Replace the current tabs with links at the top-right of the page. See #1.

This may be able to be implemented by "excluding" the tab bar in the Tab View, and controlling it programmatically.  (That may require a bit of theming. I'm not sure what the top of the pane will look like if the tabs are excluded.)

Alternatively, create a set of subclasses as was done with aiagallery.widget.RadioView, to implement a Tab View widget with a Bar that is detached and looks like links.

**Comment by derrell** [comment]
Hey @fgmart take a look!

**Comment by fgmart-zz** [comment]
awesome!  "that was easy"  (i imagine)

**Comment by derrell** [comment]
Yup. Had a "light bulb" in the shower that made it even easier. (No need to extend the Tab View; rather, just hide it, and control it externally.) Most of the time I spent was figuring out how to get the appearance of the "links" to look right.

**Comment by derrell** [comment]
"hide it" meaning hide the tab bar.

**Comment by fgmart-zz** [comment]
it is scary how much good work gets done in the shower.

**Comment by derrell** [comment]
Commit b5cef5ed5238f600ff5e1682a5b89e46c1d489ce adds a bit of theming. This is actually now starting to look half-way respectable.
