### ISSUE TITLE
When you edit info on your existing app, it re-uploads ZIP and image?

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#46]
Does the system attempt to re-upload your ZIP and source file when you just edit the text on a previously uploaded app?  It seems to from the way it messages back to the user (it says, "Uploading").

**Comment by fgmart-zz** [comment]
OK, I no longer think it does this, because I moved the source files so that they weren't in their original places, and it still updated my app properly.

So I guess the fix is... it should display "Updating..." instead of "Uploading..." when you update an existing app?

**Comment by derrell** [comment]
It's uploading your new changes. That should be visible only for a very short period of time if no zip or image file is being changed. The code would be unnecessarily complicated to add yet another status value based on what data is being uploaded, so I'm not too amenable to this change. Leaving open for further discussion in the future.

**Comment by cpuwhiz11** [comment]
Seems like this a no fix.
