### ISSUE TITLE
Problem uploading image

### ISSUE THREAD

**Issue by reedspool** [app-inventor-gallery/aig#53]
I attempted to upload a png image for an App and received a JS alert saying:

Async(undefined) exception: Error -32603: Method threw an error: Error: Database write error: JavaException: com.google.apphosting.api.ApiProxy$RequestTooLargeException: The request to API call datastore_v3.Put() was too large.

the image used can be found at 
http://tinyurl.com/aigerrorimage

**Comment by cpuwhiz11** [comment]
I think this issues has been sorted. A check is in place that limits the upload size of an image into the gallery. This image upload size is below the 1MB boundary App Engine specifies (https://developers.google.com/appengine/docs/java/datastore/overview#Quotas_and_Limits). If you had uploaded an image beyond this size you have seen that kind of exception. 

That said, given that the image link is now broken I cannot be sure if something else is going on. I did try with a number of different sized .png images and everything seems to be in order. Suggest we close this issue unless more information appears.
