### ISSUE TITLE
ensure uniqueness of display-names

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#58]
when a user logs in for the first time, check if their nickname from google is unique in our displayname database.

if so-- > OK, that is their displayname
if not-> they have their google unique ID as displayname

Also, when user tries to change his/her displayname, check if they've chosen a newly unique one, and if not, give them a "try again, that name is taken" dialog.

**Comment by derrell** [comment]
@cpuwhiz11 to you. We'll have to discuss this. It could end up as an invasive change, and I'd like to avoid that. You can begin looking at the code that automatically assigns a display name when a brand new visitor is found (identify() maybe?) and at the RPC that allows changing a display name. In both cases, we'll need to, all within a transaction, search to ensure that the display name does not already exist, and add it if it does not. IN the case of the initial display name, if it exists, use the google id number, as is already done when there is no display name available.

**Comment by fgmart-zz** [comment]
@cpuwhiz11 Paul we had conversation on this today.  We must never display the person's Gmail addr (you already know this), but neither may we ever display the numeric Google ID.  Nor should we default to the person's "nickname" from their Google account.  

So here is the new spec:

New user gets a six-character long, randomized screen name.  The first character shall be from the set [a-z], and each of the subsequent five characters from the set [0-9|a-z].  (After generating a random ID, test if it is unique; if not, repeat until this is true.)

Users may then change their screen name per the existing method.   Please allow only characters 0-9, a-z, ., _, and - in screen names.  Downcase if they use upper case.  If they try to use characters not in this set, display a helpful message; e.g. "Please use only letters, digits, and separators dash  -, underscore _, or period ." below the text field in the dialog.  (In other words, create an error message area in the existing dialog, and put the message there without the user leaving the existing dialog.)

If they specify a screen name already in use, please display "That screen name is already taken.  Please choose another." in the error area of the dialog. (Make sure to allow the case where they didn't change their name, and click OK, whereby they keep it.)

When they leave the dialog, there should be only three possible outcomes:
1.  They clicked "OK" and they have a new, unique screen name.
2.  They clicked "OK" and they have their old screen name still.
3.  They clicked "Cancel" and they have their old screen name still.

Also, please change the title bar of the edit-name dialog to "Change Screen Name".

Please let me know if this all makes sense.  Thanks.

**Comment by derrell** [comment]
Paul, here's a slight change to what Fred described.

We'll do this in two parts, one now, and one later. Because of the current design of the display name change feature, it'll take a little bit of redesign to fully implement what Fred described. Specifically, returning to the change-display-name dialog after a failure will require some changes. For the moment, do as you and I discussed yesterday. Implement the failure case by presenting a failure dialog telling the user that his requested display name is already in use, then upon click of Ok, just return to normal operation. The user can then click on his display name again, to bring up the change-display-name dialog for another try.

When there are no more release-critical items to work on, we'll put in the more appealing behavior that Fred described.

**Comment by fgmart-zz** [comment]
Thanks, Derrell.

Paul, for the case where the user tries to use characters we don't like, please display my error msg above in the dialog, and then as Derrell suggests when that gets closed, the user is back to square one.

**Comment by cpuwhiz11** [comment]
This makes sense.

**Comment by derrell** [comment]
Actually, we already have a filter in place for what characters may be entered for a display name:
<code>
          filter : /[a-zA-Z0-9 _-]/
</code>

That's in the _editProfile() method of main.Gui. This prevents entering any invalid characters, so there's no specific error message required to handle the case of an illegal name entry.

**Comment by fgmart-zz** [comment]
I like that solution -- prevent users from entering inappropriate chars in the first place :)

Is it OK to add a dot to the allowable char set?

**Comment by derrell** [comment]
Sure. The filter can contain whatever set of legal characters we want. (You also, I think, wanted to exclude upper-case letters. I'm don't happen to agree with that -- some people like all lower case; others are offended by the lack of grammatical correctness -- but this would be the place to exclude them if you really think they should be disallowed.)

**Comment by fgmart-zz** [comment]
I'm fine with upper and lower case -- as long as we do case-insensitive comparisons for uniqueness.  Is this OK?

**Comment by derrell** [comment]
Absolutely. Paul, all you need to do is make displayName in ObjVisitors be a canonicalized field, with a mapping to lower case as the canonicalization function. See ObjTags for an example.

**Comment by fgmart-zz** [comment]
OK great.  

And the legal chars are digits and letters, plus separators hyphen, underscore, space, and period ?

**Comment by derrell** [comment]
As you wish, m'Lord.

**Comment by fgmart-zz** [comment]
"Some of you may die, but that is a sacrifice I am willing to make." 

-- Lord Farquaat

**Comment by derrell** [comment]
in alpha022
