### ISSUE TITLE
Replace existing display names

### ISSUE THREAD

**Issue by derrell** [app-inventor-gallery/aig#79]
Alongside #58, we must write a one-time-use function that runs through the list of visitors assigning each of them a new base36 random value display names (and then let each visitor give himself a new display name if desired). This will re-index the newly-canonical displayName field.

@cpuwhiz11 to you
@fgmart fyi since you're watching #58

**Comment by fgmart-zz** [comment]
I think we don't need to do this, because before launch we'll be flushing the world when we move the app to the MIT instance?

**Comment by derrell** [comment]
Paul, what happens, at present, if someone tries to assign themselves a display name that is identical except for case, to one that already existed before your recent changes, i.e., one that has nothing in the new canonical displayName_lc field?

**Comment by cpuwhiz11** [comment]
I do not think this is a concern any more. Looking at the currently running mit-appinventor-gallery I checked the datastore with the following query:

SELECT \* FROM visitors WHERE displayName_lc = NULL 

There were no results so we do not have to worry about a user not having this property filled in.
