### ISSUE TITLE
during beta, put msg on home page that all projects will be deleted

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#87]
While the project is still hosted on the development instance, the home page should have text that lets all users (beta testers only, presumably) that projects (and comments etc.) _will_ be deleted before launch.

relates to #85.

**Comment by fgmart-zz** [comment]
The following specific text should be added to the text at the bottom of the current blurb, in bold face:

Please note: the App Inventor Gallery is presently in a closed beta test.  All projects, comments, etc. will be erased  before launch. 

@derrell, this is high priority; would you add this to the next build?  Thank you.

**Comment by derrell** [comment]
to me.

**Comment by derrell** [comment]
implemented with 66d30274b8ab05fd9e9780e098d11dbb8a98cd40
