### ISSUE TITLE
create and link Supported Browsers page

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#91]
put a link next to Tos and Privacy links in footer to explain supported browsers.

**Comment by derrell** [comment]
@mijoda to you

**Comment by derrell** [comment]
The fully supported browsers are Chrome and Firefox. Browsers other than IE should work for everything except uploading apps. Recent versions of IE should even work for everything except uploading apps, but formatting and colors are not presented correctly.

**Comment by mijoda** [comment]
Pull request issued with #86.  This page is pretty spare, but there's not a lot to be said.  Suggestions welcome.

**Comment by derrell** [comment]
in 023
